Entities: Add grpc entity runner
microsoft/durabletask-dotnet pull request #190
Opened 2023-09-12 16:55 UTC by jviau

This PR adds `GrpcEntityRunner` which, similar to `GrpcOrchestrationRunner`, will be used to invoke entities by durable functions.

2023-09-13 19:44 UTC, sebastianburckhardt requested changes
Looks good other than a few typos / minor issues for which I added suggestions.

2023-09-13 19:44 UTC, sebastianburckhardt commented on src/Worker/Grpc/GrpcEntityRunner.cs
> +
```suggestion

using DurableTask.Core.Entities;
using DurableTask.Core.Entities.OperationFormat;
```

2023-09-13 19:44 UTC, sebastianburckhardt commented on src/Worker/Grpc/GrpcEntityRunner.cs
> +    public static async string LoadAndRun(
```suggestion
    public static async Task<string> LoadAndRunAsync(
```

2023-09-13 19:44 UTC, sebastianburckhardt commented on src/Worker/Grpc/GrpcEntityRunner.cs
> +        EntityId id = EntityId.FromString(batch.InstanceId);
```suggestion
        EntityId id = EntityId.FromString(batch.InstanceId!);
```

2023-09-13 19:44 UTC, sebastianburckhardt commented on src/Worker/Grpc/GrpcEntityRunner.cs
> +        EntityBatchReqesult result = await entity.ExecuteOperationBatchAsync(batch);
```suggestion
        EntityBatchResult result = await entity.ExecuteOperationBatchAsync(batch);
```

2023-09-13 19:44 UTC, sebastianburckhardt commented on src/Worker/Grpc/GrpcEntityRunner.cs
> +        byte[] responseBytes = result.ToByteArray();
```suggestion
        byte[] responseBytes = response.ToByteArray();
```

2023-09-14 17:17 UTC, jviau commented
> Looks good other than a few typos / minor issues for which I added suggestions.

😅 guess I am sloppy without full language service / IDE

2023-09-14 17:23 UTC, sebastianburckhardt approved these changes

2023-09-21 20:35 UTC, merged